In [1]:
import numpy as np

In [2]:
firstArray = np.array ([1, 2, 3], dtype = 'int32')

In [3]:
firstArray

array([1, 2, 3])

In [4]:
secondArray = np.array ([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

In [5]:
secondArray.shape

(2, 3)

In [6]:
secondArray.ndim

2

In [7]:
secondArray.dtype

dtype('float64')

In [8]:
secondArray.size

6

#### Indexing

In [9]:
secondArray

array([[9., 8., 7.],
       [6., 5., 4.]])

In [10]:
secondArray[1, 1]

5.0

In [11]:
secondArray[0, :]

array([9., 8., 7.])

In [12]:
secondArray[:, 1]

array([8., 5.])

In [13]:
### [startindex:endindex:steps]

In [14]:
secondArray[0, 1:-1:1]

array([8.])

In [15]:
secondArray

array([[9., 8., 7.],
       [6., 5., 4.]])

In [16]:
secondArray[1, 2] = 10

In [17]:
secondArray

array([[ 9.,  8.,  7.],
       [ 6.,  5., 10.]])

In [18]:
np.ones ((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros ((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.full ((3, 3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [21]:
np.identity (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 3-D Tensor Example

In [22]:
tensor = np.array (
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
)

In [23]:
tensor[0, 1, 1]

4

In [24]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
tensor[:, 1, :] = [[9, 9], [8, 8]]

In [26]:
tensor

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Random Matrix

In [32]:
np.random.rand (4, 2)

array([[0.93435448, 0.26285577],
       [0.64740105, 0.02785513],
       [0.48161114, 0.40097853],
       [0.71777909, 0.16221966]])

In [42]:
np.random.randint (-4, 8, size = (3, 3), dtype='int32')

array([[ 0, -2, -2],
       [-2,  3,  5],
       [-4,  4,  5]])

In [43]:
firstArray

array([1, 2, 3])

In [44]:
firstArray + 2

array([3, 4, 5])

In [45]:
firstArray * 2

array([2, 4, 6])

### Linear Algebra

In [48]:
identityMatrix = np.identity (5, dtype='int64')

In [50]:
identityMatrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [51]:
int (np.linalg.det (identityMatrix))

1

In [52]:
firstArray = np.ones ((1000, 1000))
secondArray = np.zeros ((1000, 1000))

In [53]:
from time import perf_counter

In [54]:
startTime = perf_counter ()
dotProduct = np.dot (firstArray, secondArray)
endTime = perf_counter ()
print (f'Time taken {endTime - startTime}')

Time taken 0.09458769999946526


In [55]:
startTime = perf_counter ()
dotProduct = np.matmul (firstArray, secondArray)
endTime = perf_counter ()
print (f'Time taken {endTime - startTime}')

Time taken 0.04447309999886784


In [56]:
startTime = perf_counter ()
dotProduct = firstArray @ secondArray
endTime = perf_counter ()
print (f'Time taken {endTime - startTime}')

Time taken 0.0402472999994643


### Reorganizing Structures

#### Vertical Structuring

In [57]:
v1 = np.array ([1, 2, 3, 4])
v2 = np.array ([5, 6, 7, 8])

In [58]:
np.vstack ([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Horizontal Stacking

In [60]:
h1 = np.ones ((2, 2))
h2 = np.zeros ((2, 2))

In [61]:
np.hstack ([h1, h2, h1])

array([[1., 1., 0., 0., 1., 1.],
       [1., 1., 0., 0., 1., 1.]])

### Reshape

In [62]:
before = np.array ([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
after = before.reshape ((-1, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])